### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by dominikgeimer** [concept7/filament-invite#6]
Hi,

can you describe how to use this after the installation?

Thanks!

**Comment by dominikgeimer** [comment]
Hi, 

sounds good! Meanwhile I have implemented my own invitation with https://github.com/spatie/laravel-welcome-notification

But I will also try your solution.

"The package will be sending out invite emails by listening to the 'created'-event on user model. "

Is it also triggered when a user just registered to the app (I mean the default registration, not via invite).

**Comment by mwagena** [comment]
We needed a solution in which the user has the possibility to setup his own
password.

Op wo 13 sep. 2023 16:46 schreef Dominik Geimer ***@***.***>:
